services:
  sirati-mustakim:
    image: postgres:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: fatehzaliyev
      POSTGRES_PASSWORD: ucai6chietee7ak8aiFi
      POSTGRES_DB: maindb
    networks:
      - postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: fatehzaliyev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ucai6chietee7ak8aiFi
    networks:
      - postgres
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411:9411'

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: