spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/maindb
    username: fatehzaliyev
    password: ucai6chietee7ak8aiFi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddlAuto: create-drop
    showSql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 1111111111111
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days